version: "3.3"
services:
  mysql-server-1:
    env_file:
      - mysql-server.env
    image: mysql/mysql-server:8.0.13
    ports:
      - "3301:3306"
    command: ["mysqld","--server_id=1","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    healthcheck:
      test: "exit 0"
    networks:
      - blog-net
    volumes:
      - db-1-data:/var/lib/mysql

  mysql-server-2:
    env_file:
      - mysql-server.env
    image: mysql/mysql-server:8.0.13
    command: ["mysqld","--server_id=2","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    ports:
      - "3302:3306"
    healthcheck:
      test: "exit 0"
    networks:
      - blog-net
    volumes:
      - db-2-data:/var/lib/mysql

  mysql-server-3:
    env_file:
      - mysql-server.env
    image: mysql/mysql-server:8.0.13
    command: ["mysqld","--server_id=3","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    ports:
      - "3303:3306"
    healthcheck:
      test: "exit 0"
    networks:
      - blog-net
    volumes:
      - db-3-data:/var/lib/mysql

  mysql-shell:
    env_file:
      - mysql-shell.env
    image: bkandasa/mysql-shell-batch
    volumes:
        - ./scripts/:/scripts/
    depends_on:
      mysql-server-1:
          condition: service_healthy
      mysql-server-2:
          condition: service_healthy
      mysql-server-3:
          condition: service_healthy
    restart: on-failure
    networks:
      - blog-net

  mysql-router:
    env_file:
      - mysql-router.env
    image: mysql/mysql-router:8.0.13
    ports:
      - 6446:6446
      - 6447:6447
    depends_on:
      mysql-server-1:
          condition: service_healthy
      mysql-server-2:
          condition: service_healthy
      mysql-server-3:
          condition: service_healthy
      mysql-shell:
          condition: service_started
    restart: on-failure
    networks:
      - blog-net

  phpmyadmin:
    image: phpmyadmin
    container_name: msr-phpmyadmin
    depends_on:
      - mysql-router
    ports:
      - 8181:80
    env_file:
      - phpmyadmin.env
    networks:
      - blog-net

  backend:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    depends_on:
      - mysql-router
    env_file:
      - .env
    ports:
      - 8800:8800
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - blog-net
    restart: on-failure

volumes:
  db-1-data:
  db-2-data:
  db-3-data:

networks:
  blog-net:
    driver: bridge

